### ISSUE TITLE
I cannot start it.

### ISSUE THREAD

**Issue by michaltaberski** [ikoma-ciklum/getVocal_ikoma-test#1]
![CleanShot 2024-10-10 at 19 46 24](https://github.com/user-attachments/assets/1ec7b850-1ec9-4f4d-9b96-59208e8c6673)

## Please deploy it somewhere and provide url or provide run description.

**Comment by ikoma-ciklum** [comment]
@michaltaberski just updated the repo. should work now. instructions are the same ones
